{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef }}
    kind: SecretStore
  target:
    name: {{ .Values.database.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.database.usernameKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretArn }}
        property: username
    - secretKey: {{ .Values.database.passwordKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretArn }}
        property: password
{{- end }}
